version: '3.7'

services:
  database-checkout:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: checkout
    container_name: db-checkout
    ports:
      - 5432:5432