package org.diotutorial.ecommerce.checkout.resource.checkout;

import lombok.RequiredArgsConstructor;
import org.diotutorial.ecommerce.checkout.event.CheckoutCreatedEvent;
import org.diotutorial.ecommerce.checkout.streaming.CheckoutCreatedSource;
import org.springframework.http.ResponseEntity;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@CrossOrigin
@RestController
@RequestMapping("/v1/checkout")
@RequiredArgsConstructor
public class CheckoutResource {

    private final CheckoutCreatedSource checkoutCreatedSource;


    @PostMapping("/")
    public ResponseEntity<Void> create(CheckoutRequest checkoutRequest) {
        // CheckoutCreatedEvent is generated by avro plugin, check build/generated-main-avro-java
        final CheckoutCreatedEvent checkoutCreatedEvent =
                CheckoutCreatedEvent.newBuilder()
                    .setCheckoutCode("123")
                    .build();

        checkoutCreatedSource.output().send(MessageBuilder.withPayload(checkoutCreatedEvent).build());
        return ResponseEntity.ok().build();
    }
}
